# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - id: gitlabcli
    binary: gitlabcli
    main: ./cmd/gitlabcli.go
    ldflags: -s -w -X github.com/apenella/gitlabcli/internal/release.BuildDate={{.Date}} -X github.com/apenella/gitlabcli/internal/release.Version={{ .Tag }} -X github.com/apenella/gitlabcli/internal/release.Commit={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - id: gitlabcli
    builds:
      - gitlabcli
    format: tar.gz
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

checksum:
  name_template: '{{.ProjectName}}_{{.Version}}_checksums.txt'
snapshot:
  name_template: '{{.ProjectName}}_{{ .Version }}'
changelog:
  skip: false
